### ISSUE TITLE
Home Page Tweaks/Fixes

### ISSUE THREAD

**Issue by brentrobbins** [variantstudios/optirtc.com#62]
*If you have any questions let me know before you get started.*
- [x] "Under the Customer bar: At full width on a desktop screen, there is a light blue section that appears between the customer and case study sections."
- [x] "View More Opti Products Button: At certain browser widths the button’s right border disappears (actually happens with our old page too)"

#### Please make sure you document with jump share screenshots before and after so we can show them side-by-side what you did.

**Comment by danieljauch** [comment]
Issue 1:
Before: http://jmp.sh/RXhVddN
The issue was that the content inside of the box was going beneath even though the wrapper didn't extend that far. Here's a highlighted box of the inner content that is too large: http://jmp.sh/meHxHGQ
And here is the fixed product once the extra margin is removed: http://jmp.sh/GgvxF6n

Issue 2:
Before: http://jmp.sh/8mzTsSl
The issue is that "width: auto" on the anchor element is for some reason calculating a pixel width that isn't exact, so when the width is a partial pixel, it either rounds down or up, when it rounds down, it cuts the border, when it rounds up, it doesn't. It's just how it's drawn. I've created pixel widths for each button effected (there were actually more than just this one) so that it won't round it out on higher breakpoints: http://jmp.sh/4s1rngQ
Still full-width in mobile
